"""
Customers Responses Package
"""

from .customer_docs import (
    CREATE_ADDRESS_RESPONSES,
    DELETE_ADDRESS_RESPONSES,
    GET_PROFILE_RESPONSES,
    LIST_ADDRESSES_RESPONSES,
    UPDATE_ADDRESS_RESPONSES,
    UPDATE_PROFILE_RESPONSES,
)

__all__ = [
    "GET_PROFILE_RESPONSES",
    "UPDATE_PROFILE_RESPONSES",
    "LIST_ADDRESSES_RESPONSES",
    "CREATE_ADDRESS_RESPONSES",
    "UPDATE_ADDRESS_RESPONSES",
    "DELETE_ADDRESS_RESPONSES",
]
