"""
Inventory Responses Package
"""

from .inventory_docs import (
    CREATE_INVENTORY_RESPONSES,
    DELETE_INVENTORY_RESPONSES,
    GET_INVENTORY_BY_SKU_RESPONSES,
    GET_INVENTORY_RESPONSES,
    LIST_INVENTORY_RESPONSES,
    UPDATE_INVENTORY_RESPONSES,
)

__all__ = [
    "CREATE_INVENTORY_RESPONSES",
    "GET_INVENTORY_RESPONSES",
    "GET_INVENTORY_BY_SKU_RESPONSES",
    "LIST_INVENTORY_RESPONSES",
    "UPDATE_INVENTORY_RESPONSES",
    "DELETE_INVENTORY_RESPONSES",
]
