from .returns_docs import (
    ADMIN_UPDATE_RETURN_RESPONSES,
    CREATE_RETURN_RESPONSES,
    GET_RETURN_RESPONSES,
)

__all__ = [
    "CREATE_RETURN_RESPONSES",
    "GET_RETURN_RESPONSES",
    "ADMIN_UPDATE_RETURN_RESPONSES",
]
