"""Admin Responses Package"""

from .admin_docs import (
    CREATE_SHIPMENT_RESPONSES,
    GET_ORDER_DETAIL_RESPONSES,
    LIST_ORDERS_RESPONSES,
    PACKING_SLIP_RESPONSES,
    PICK_LIST_RESPONSES,
    SHIP_ORDER_RESPONSES,
    STATUS_OVERRIDE_RESPONSES,
)

__all__ = [
    "LIST_ORDERS_RESPONSES",
    "PICK_LIST_RESPONSES",
    "GET_ORDER_DETAIL_RESPONSES",
    "STATUS_OVERRIDE_RESPONSES",
    "PACKING_SLIP_RESPONSES",
    "CREATE_SHIPMENT_RESPONSES",
    "SHIP_ORDER_RESPONSES",
]
