"""OpenAPI response documentation for mail endpoints."""

from .mail_docs import (
    ATTACHMENT_RESPONSES,
    CREATE_FOLDER_RESPONSES,
    DELETE_FOLDER_RESPONSES,
    DELETE_MESSAGE_RESPONSES,
    FOLDER_RESPONSES,
    LIST_MESSAGES_RESPONSES,
    MESSAGE_RESPONSES,
    MOVE_MESSAGE_RESPONSES,
    RENAME_FOLDER_RESPONSES,
    SEND_MESSAGE_RESPONSES,
    STATUS_RESPONSES,
    UPDATE_FLAGS_RESPONSES,
)

__all__ = [
    "ATTACHMENT_RESPONSES",
    "CREATE_FOLDER_RESPONSES",
    "DELETE_FOLDER_RESPONSES",
    "DELETE_MESSAGE_RESPONSES",
    "FOLDER_RESPONSES",
    "LIST_MESSAGES_RESPONSES",
    "MESSAGE_RESPONSES",
    "MOVE_MESSAGE_RESPONSES",
    "RENAME_FOLDER_RESPONSES",
    "SEND_MESSAGE_RESPONSES",
    "STATUS_RESPONSES",
    "UPDATE_FLAGS_RESPONSES",
]
